//! Feasibility spike: `any_non_default()`, generated by `#[derive(Args)]`, naming the first
//! field whose value differs from `Self::default()`. Not a real feature yet — proves the
//! codegen compiles and behaves, for a jdx/usage#???? proposal.

use usage_derive::Args;

#[derive(Args, Debug, Default, PartialEq)]
#[usage(diff_from_default)]
struct MergeFlags {
    #[usage(short = 'a', long)]
    ask: bool,
    #[usage(short = 'u', long)]
    update: bool,
    #[usage(short = 'D', long)]
    deep: bool,
    #[usage(long)]
    exclude: Vec<String>,
    #[usage(long)]
    jobs: Option<u32>,
}

#[test]
fn every_field_default_is_none() {
    let flags = MergeFlags::default();
    assert_eq!(flags.any_non_default(), None);
}

#[test]
fn one_bool_flag_set_is_named_with_its_value() {
    let flags = MergeFlags {
        ask: true,
        ..Default::default()
    };
    assert_eq!(flags.any_non_default(), Some(("--ask", "true".to_string())));
}

#[test]
fn a_later_field_is_found_when_earlier_ones_are_default() {
    let flags = MergeFlags {
        deep: true,
        ..Default::default()
    };
    assert_eq!(flags.any_non_default(), Some(("--deep", "true".to_string())));
}

#[test]
fn a_vec_field_renders_via_debug() {
    let flags = MergeFlags {
        exclude: vec!["foo".to_string(), "bar".to_string()],
        ..Default::default()
    };
    assert_eq!(
        flags.any_non_default(),
        Some(("--exclude", "[\"foo\", \"bar\"]".to_string()))
    );
}

#[test]
fn an_option_field_renders_via_debug() {
    let flags = MergeFlags {
        jobs: Some(8),
        ..Default::default()
    };
    assert_eq!(flags.any_non_default(), Some(("--jobs", "Some(8)".to_string())));
}

#[test]
fn only_the_first_differing_field_is_reported() {
    let flags = MergeFlags {
        ask: true,
        deep: true,
        ..Default::default()
    };
    // Declaration order: ask comes before deep.
    assert_eq!(flags.any_non_default(), Some(("--ask", "true".to_string())));
}
